call plug#begin('~/.vim/plugged')
	Plug 'morhetz/gruvbox'
call plug#end()


nnoremap <silent> .cpp :-1read C:\Users\GOURANGO MODAK\Downloads\Competitive_Programming\Miscellanious\temp.cpp<CR>6jwf{

"Navigate Panel

nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>
nmap <silent> <C-j> :wincmd j<CR>

set wildmenu
set path+=C:/Users/GOURANGO\\\ MODAK/Downloads/Competitive_Programming/**


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Splits and Tabbed Files
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set splitbelow splitright


" Remap ESC to ii
:imap ii <Esc>

set laststatus=2
set statusline=
set statusline +=%*\ %n\ %*            "buffer number
set statusline+=%#LineNr#
set statusline +=%4*\ %<%F            "full path
set statusline+=%=
set statusline+=%#LineNr#
set statusline+=\ %p%%
set statusline+=\ %l
set statusline+=\ 

colorscheme gruvbox
set background=dark
set cursorline
syntax on
set smartcase ignorecase
set scrolloff=10
set noerrorbells
set autoindent
set copyindent
set wrap
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set incsearch
set clipboard=unnamed
set encoding=utf-8
set backspace=2
set nu
if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14
  elseif has("gui_win32")
    set guifont=Consolas:h14:cANSI
    map <F11> <Esc>:call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<CR>

    "Full screen mode

    set guioptions-=m  "remove menu bar
    set guioptions-=T  "remove toolbar
    set guioptions-=r  "remove right-hand scroll bar
    set guioptions-=L  "remove left-hand scroll bar
  endif
endif


nnoremap <silent> <C-b> :!g++ -std=c++17 % -o %:r<CR>
nnoremap <silent> <C-p> :!%:r <CR>
nnoremap <silent> cwd :cd ./Downloads/Competitive_Programming/Problems/<CR>
